### List all messages
GET  http://localhost:3000/messages

### Post a message
POST http://localhost:3000/messages
content-type: "application/json"
{
  "message": "Hello There!"
}

### Get a particular Message
GET http://localhost:3000/messages/1